# Nome do seu fluxo de trabalho. Aparecerá na aba "Actions" do seu repositório.
name: Executar Testes Cypress

# Define o gatilho (trigger) para o workflow.
# Neste caso, ele será executado a cada 'push' para a branch 'main'.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define os "jobs" (tarefas) que serão executados.
jobs:
  cypress-run:
    # O tipo de máquina virtual que será usada para executar o job.
    runs-on: ubuntu-latest
    
    # Os passos que compõem o job.
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v6